version: '1.0'
services:
  postgres:
    container_name: postgresExpenseDB
    image: postgres
    volumes:
      - postgres-expense-data:/var/lib/postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DATABASE: expensesDB
      POSTGRES_PASSWORD: angad@db
    networks:
      - expense-details-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'angadraut89@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: angad@db
    ports:
      - 16544:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - expense-details-network

  expense-service-app:
    image: expense-details
    restart: always
    build: .
    ports:
      - 1992:1992
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgresExpenseDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: angad@db
      POSTGRES_PORT: 5432
    networks:
      - expense-details-network

networks:
  expense-details-network:
    driver: bridge

volumes:
  postgres-expense-data:
    driver: local
